suxess-it/kubriX

- platform-apps/charts/team-onboarding/values-uibklab.yaml
update for team team-a onboarding
> Update for team team-a

- platform-apps/charts/team-onboarding/values-uibklab.yaml
Onboarding team team-a onboarding
> Onboarding team team-a

- platform-apps/charts/mimir/values-k3d.yaml
- platform-apps/charts/mimir/values-uibklab.yaml
fixes https://github.com/suxess-it/sx-cnp-oss/issues/399
> set memory and cpu limit to override kyverno limitrange default

- platform-apps/charts/kyverno/templates/policy-add-ns-quota.yaml
with https://github.com/suxess-it/sx-cnp-oss/pull/401 we increased memory and cpu limits, so we needed to adjust also the kyverno resourcequota
> increase kyverno resourcequota limits for mimir distributed limits

- platform-apps/charts/kyverno/templates/policy-add-ns-quota.yaml
- platform-apps/charts/mimir/values-k3d.yaml
- platform-apps/charts/mimir/values-uibklab.yaml
fixes https://github.com/suxess-it/sx-cnp-oss/issues/417
> fix: increase ingester resource limits

- platform-apps/charts/mimir/templates/mimir-datasource.yaml
fix https://github.com/suxess-it/sx-cnp-oss/issues/440
> feat: set mimir datasource as default

- platform-apps/charts/grafana/dashboard-files/k8s-system-api-server.json
- platform-apps/charts/grafana/dashboard-files/k8s-system-coredns.json
- platform-apps/charts/grafana/dashboard-files/k8s-views-global.json
- platform-apps/charts/grafana/dashboard-files/k8s-views-namespaces.json
- platform-apps/charts/grafana/dashboard-files/k8s-views-nodes.json
- platform-apps/charts/grafana/dashboard-files/k8s-views-pods.json
fix https://github.com/suxess-it/sx-cnp-oss/issues/440
> set default datasource in kubernetes dashboards

- platform-apps/charts/team-onboarding/templates/app-project.yaml
fixes https://github.com/suxess-it/sx-cnp-oss/issues/306
> delete project after apps

- platform-apps/charts/grafana/values-metalstack.yaml
- platform-apps/charts/k8s-monitoring/values-metalstack.yaml
- platform-apps/charts/loki/values-metalstack.yaml
- platform-apps/charts/mimir/values-metalstack.yaml
> add values for metalstack

- platform-apps/charts/team-onboarding/values-uibklab.yaml
> Onboarding team uibklab

- .devcontainer/kind-config.yaml
solves https://github.com/suxess-it/sx-cnp-oss/issues/637
> add ingress port mappings in devcontainer kind

- .github/create-pr-comment-file.sh
.. but not all needed values, which could end in helm template errors
> ignore values.yaml because this often just defines defaults

- .github/workflows/cluster-test.yml
solves https://github.com/suxess-it/kubriX/issues/914
> run github actions only when needed

- platform-apps/charts/team-onboarding/templates/app-project.yaml
- platform-apps/charts/team-onboarding/templates/argocd-credential-template-es.yaml
fixes https://github.com/suxess-it/kubriX/issues/1087
> feat: create credential-template automatically during onboarding

- platform-apps/charts/loki/values.yaml
- platform-apps/charts/mimir/values.yaml
- platform-apps/charts/tempo/values.yaml
fixes https://github.com/suxess-it/kubriX/issues/1070
> feat(observability): set default retention of 30 days

- platform-apps/charts/vault/templates/crossplane/cp-provider.yaml
solves https://github.com/suxess-it/kubriX/issues/1083
> fix: reduce pollInterval to speed up installation, solves #1083

- platform-apps/charts/argocd/values-k3d.yaml
fixes https://github.com/suxess-it/kubriX/issues/1112
> feat(argocd): application should only be healthy when also synced

- install-platform.sh
- platform-apps/charts/team-onboarding/templates/appset-scm-multi-stage-kargo-es.yaml
- platform-apps/charts/team-onboarding/templates/argocd-credential-template-es.yaml
- team-apps/onboarding-apps-charts/multi-stage-app-with-kargo-pipeline/README.md
> fix(delivery): streamline variable names

- .secrets/.envoss.yaml
- bootstrap/BOOTSTRAP-local-kind.md
- bootstrap/BOOTSTRAP.md
- bootstrap/bootstrap.sh
- install-platform.sh
- kubrix-local-installation.md
- kubrix-playground-github-codespaces.md
- platform-apps/charts/backstage/templates/es-backstage-secret.yaml
fixes https://github.com/suxess-it/kubriX/issues/1317 and https://github.com/suxess-it/kubriX/issues/1341
> feat(installer): use .secrets framework for github oauth app secrets

- install-platform.sh
- platform-apps/charts/backstage/templates/backstage-locator-token-pushsecret.yaml
- platform-apps/charts/backstage/templates/es-backstage-secret.yaml
fixes https://github.com/suxess-it/kubriX/issues/1341
> feat(installer): put all backstage secrets in vault

- .github/workflows/create-kubrix-installer-image.yml
- Dockerfile
- install-manifests.yaml
- install-platform.sh
fixes https://github.com/suxess-it/kubriX/issues/1491
> feat(installer): run installer in Kubernetes Job

- .secrets/.envoss.yaml
- install-platform.sh
- platform-apps/charts/velero-ui/Chart.lock
- platform-apps/charts/velero-ui/Chart.yaml
- platform-apps/charts/velero-ui/templates/external-secret.yaml
- platform-apps/charts/velero-ui/values-demo-metalstack.yaml
- platform-apps/charts/velero-ui/values-demo-stack.yaml.tmpl
- platform-apps/charts/velero-ui/values-k3d.yaml
- platform-apps/charts/velero/Chart.lock
- platform-apps/charts/velero/Chart.yaml
- platform-apps/charts/velero/dashboard-files/velero-dashboard-16829.json
- platform-apps/charts/velero/templates/external_secret_repo_credential.yaml
- platform-apps/charts/velero/templates/external_secret_velero.yaml
- platform-apps/charts/velero/values-demo-metalstack.yaml
- platform-apps/charts/velero/values-demo-stack.yaml.tmpl
- platform-apps/charts/velero/values-k3d.yaml
- platform-apps/charts/velero/values.yaml
> feat(velero,vui): update helm releases and change kubectl to bitnamilegacy

- docs/oss/installation/quick-start-kubernetes.md
Updated the supported DNS providers for external-dns.
> chore(docs): Change supported DNS provider from route53 to aws

- install-platform.sh
Added kubectl commands to describe and list nodes and managed resources.
> feat(installer): add troubleshooting output

- docs/oss/installation/installation.md
Removed helm, git, jq, yq, and mkcert from the installation requirements.
> chore(docs): Update installation requirements in documentation

- platform-apps/charts/k8s-monitoring/values-k3d.yaml
- platform-apps/charts/loki/templates/loki-datasource.yaml
- platform-apps/charts/loki/values-demo-metalstack.yaml
- platform-apps/charts/loki/values-demo-stack.yaml.tmpl
- platform-apps/charts/loki/values-k3d.yaml
fixes https://github.com/suxess-it/kubriX/issues/1575
> feat(loki): switch to simple scalable mode
